// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvnetskbvtkdfcexxhjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bmV0c2tidnRrZGZjZXh4aGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzkzODgsImV4cCI6MjA1NzExNTM4OH0.tUJ2fgveJjPIPNIRvvKUbETHEpRD6vMR94-SpFsmr2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);